- name: Install Memcached
  apt:
    name:
      - memcached
      - python3-memcache
    state: present
    update_cache: yes

- name: Restarting Memcached
  service:
    name: memcached
    state: restarted
    enabled: yes
